title: [30 Days of Code Challenge]
description: [Improve your coding skills by coding for 30 days]
show_downloads: ["true"]
theme: jekyll-theme-cayman
language: java
google_analytics: [UA-144702039-1]
