title: [30 Days of Code Challenge]
description: [Every day for 30 days, you will receive an email posing a challenge for you to code, solve, and submit the solution.]
theme: jekyll-theme-cayman
language: java
